### ISSUE TITLE
trying to move to modular deps

### ISSUE THREAD

**Issue by pachamaltese** [pachamaltese/d3plus-r#19]
Hi @jbkunst and @gvegayon 

I was trying to move to modular deps with the aim of:

1. being up-to-date with cool new D3plus methods
2. make this more lightweight since this does not implement all of D3plus methods (yet)

So I edited d3plus.yaml and I broke the package XD

This example:
```
dta4 <- tibble(parent = c(rep("Group 1",3), rep("Group 2",2)),
               id = c("alpha","beta","gamma","delta","eta"),
               value = c(29,10,2,29,25))

d3plus() %>% 
  d3p_type("treemap") %>% 
  d3p_data(dta4) %>% 
  d3p_groupby(c("parent","id"))
```

Returns errors
![screenshot from 2017-12-16 15-43-50](https://user-images.githubusercontent.com/10091065/34073401-ed5ea46c-e277-11e7-89e9-a285691c97c4.png)

Any ideas?

**Comment by pachamaltese** [comment]
what I did from my local dir was to build the modules:
```
https://github.com/d3plus/d3plus-hierarchy
cd '/home/pacha/GitHub/d3plus/d3plus-hierarchy'
git pull
npm install
npm run-script build
cp '/home/pacha/GitHub/d3plus/d3plus-hierarchy/build/d3plus-hierarchy.min.js' '/home/pacha/GitHub/d3plus/r-package/inst/htmlwidgets/lib/d3plus/d3plus-hierarchy.min.js'
```

the strange part is that in the yaml file if I switch 
```
  - name: d3plus-hierarchy
    version: 2.0.0
    src: htmlwidgets/lib/d3plus
    script:
      - d3plus-hierarchy.min.js
```

to
```
  - name: d3plus-hierarchy
    version: 2.0.0
    src: htmlwidgets/lib/d3plus
    script:
      - d3plus-hierarchy.full.min.js
```

treemaps work then but XY plots won't work doing this:
```
  - name: d3plus-plot
    version: 2.0.0
    src: htmlwidgets/lib/d3plus
    script:
      - d3plus-plot.full.min.js
```
